# -*- coding: utf-8 -*-
"""face_recog_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E58vCyrojO6tGo5nQY8H63yOQGLOqlE3
"""

import streamlit as st
import numpy as np
import cv2
import os
import pickle

from mtcnn import MTCNN
from keras_facenet import FaceNet
from sklearn.neighbors import KNeighborsClassifier

# Initialize
detector = MTCNN()
embedder = FaceNet()

DATASET_PATH = "dataset"
MODEL_PATH = "model.pkl"

os.makedirs(DATASET_PATH, exist_ok=True)

# Sidebar
st.sidebar.title("Face Recognition App")
menu = st.sidebar.selectbox(
    "Choose Feature",
    ["Register Person", "Train Model", "Recognize Face", "View Dataset"]
)

# ---------------- REGISTER PERSON ----------------
if menu == "Register Person":
    st.title("📸 Register New Person")

    person_name = st.text_input("Enter Person Name")
    uploaded_files = st.file_uploader(
        "Upload Images",
        accept_multiple_files=True,
        type=["jpg", "png", "jpeg"]
    )

    if st.button("Save Images"):
        if person_name and uploaded_files:
            person_path = os.path.join(DATASET_PATH, person_name)
            os.makedirs(person_path, exist_ok=True)

            for file in uploaded_files:
                file_path = os.path.join(person_path, file.name)
                with open(file_path, "wb") as f:
                    f.write(file.read())

            st.success("Images saved successfully ✅")
        else:
            st.warning("Please enter name and upload images")

# ---------------- TRAIN MODEL ----------------
elif menu == "Train Model":
    st.title("🧠 Train Face Recognition Model")

    if st.button("Train"):
        X = []
        y = []

        for person in os.listdir(DATASET_PATH):
            person_path = os.path.join(DATASET_PATH, person)

            for img_name in os.listdir(person_path):
                img_path = os.path.join(person_path, img_name)

                img = cv2.imread(img_path)
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

                faces = detector.detect_faces(img)

                if faces:
                    x, y_, w, h = faces[0]['box']
                    face = img[y_:y_+h, x:x+w]
                    face = cv2.resize(face, (160,160))

                    embedding = embedder.embeddings([face])[0]

                    X.append(embedding)
                    y.append(person)

        model = KNeighborsClassifier(n_neighbors=3)
        model.fit(X, y)

        with open(MODEL_PATH, "wb") as f:
            pickle.dump(model, f)

        st.success("Model trained successfully 🎉")

# ---------------- RECOGNIZE FACE ----------------
elif menu == "Recognize Face":
    st.title("🔍 Recognize Face")

    uploaded_file = st.file_uploader(
        "Upload Image",
        type=["jpg", "png", "jpeg"]
    )

    if uploaded_file is not None:
        file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
        img = cv2.imdecode(file_bytes, 1)
        rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        st.image(rgb, caption="Uploaded Image", use_column_width=True)

        if os.path.exists(MODEL_PATH):
            with open(MODEL_PATH, "rb") as f:
                model = pickle.load(f)

            faces = detector.detect_faces(rgb)

            if faces:
                x, y_, w, h = faces[0]['box']
                face = rgb[y_:y_+h, x:x+w]
                face = cv2.resize(face, (160,160))

                embedding = embedder.embeddings([face])[0]

                distance, _ = model.kneighbors([embedding], n_neighbors=1)

                threshold = 0.8

                if distance[0][0] < threshold:
                    prediction = model.predict([embedding])
                    st.success(f"Recognized as: {prediction[0]} ✅")
                else:
                    st.error("Unknown Person ❌")

                st.write("Confidence Distance:", distance[0][0])

            else:
                st.warning("No face detected")
        else:
            st.warning("Train model first")

# ---------------- VIEW DATASET ----------------
elif menu == "View Dataset":
    st.title("📂 Dataset Overview")

    persons = os.listdir(DATASET_PATH)

    for person in persons:
        st.subheader(person)
        person_path = os.path.join(DATASET_PATH, person)

        cols = st.columns(5)
        i = 0

        for img_name in os.listdir(person_path):
            img_path = os.path.join(person_path, img_name)
            img = cv2.imread(img_path)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            cols[i].image(img)
            i = (i + 1) % 5